# Generated by Django 6.0.5 on 2026-05-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('evidence_url', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_latitude', models.FloatField()),
                ('gps_longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Mpya / Imepokelewa'), ('UNDER_INVESTIGATION', 'Inachunguzwa'), ('RESOLVED', 'Imeshitakiwa / Imekwisha')], default='NEW', max_length=30)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.crimetype')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimes.district')),
            ],
        ),
    ]
