# Generated by Django 6.0.5 on 2026-05-18 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_alter_crimereport_evidence_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crimes.district'),
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Kituo')),
                ('latitude', models.FloatField(verbose_name='GPS Latitude')),
                ('longitude', models.FloatField(verbose_name='GPS Longitude')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Namba ya Simu ya Kituo')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='crimes.district', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name_plural': 'Vituo vya Polisi',
            },
        ),
        migrations.AddField(
            model_name='crimereport',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='crimes.policestation', verbose_name='Kituo Kilichopangiwa Tukio'),
        ),
    ]
