"""
Django settings for ctas_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w!4s=88q*28ssc!s2*f48ay2_36=*ooc#c5-8#i3npfp!&3_&@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',  # <-- Kagua hapa! Hakikisha neno 'contrib' lipo na hakuna herufi iliyofutika
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken', 
    'crimes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ctas_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ctas_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
import os # <-- Hakikisha hii ipo juu au iweke hapa chini

# Njia ya folda ambapo picha halisi zitahifadhiwa kwenye kompyuta yako
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL itakayotumika kufungua picha hizo kwenye browser (mfano: http://127.0.0.1:8000/media/picha.jpg)
MEDIA_URL = '/media/'
CORS_ALLOW_ALL_ORIGINS = True
# RUHUSU SEVA IPKEE VITAMBULISHO VYA ULINZI (COOKIES/SESSIONS) KUTOKA FRON

# Hakikisha origins zako zimeruhusiwa vizuri (pamoja na anwani za localhost)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",
    "http://127.0.0.1:5500",
    "http://localhost:3000",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization", # <--- Hii ndio inaruhusu Token ya Polisi isizuiliwe
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # <--- Tunalazimisha mifumo isome Token pekee
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # <--- BADILISHA AllowAny IWE IsAuthenticated!
    ],
}

# =======================================================
# JAZZMIN ADMIN THEME CONFIGURATION 🛡️🎨
# =======================================================
JAZZMIN_SETTINGS = {
    "site_title": "CTAS Admin",
    "site_header": "CTAS COMMAND CENTER",
    "site_brand": "CTAS ADMIN 🛡️",
    "welcome_sign": "Karibu kwenye Mfumo Mkuu wa Usimamizi (CTAS Admin)",
    "copyright": "Jeshi la Polisi CTAS Automation Team",
    "search_model": ["auth.User", "crimes.CrimeReport"],
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # VIUNGANISHI VYA JUU
    "topmenu_links": [
        {"name": "Ukurasa Mkuu (Home)", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # Mipangilio mingine ya Jazzmin
    "use_google_fonts": True,
    "custom_links": {}, 
    
    # Icons kwa ajili ya Model zako (Zinatumia FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "crimes.CrimeReport": "fas fa-exclamation-triangle",
        "crimes.District": "fas fa-map-marked-alt",
        "authtoken.tokenproxy": "fas fa-key",
    },
}

# Muonekano wa rangi za Giza (Dark Mode)
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",      
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-primary",
}

# Mipangilio ya Usalama wa Vikao na CSRF (Inazuia migogoro ya logout kwenye Ubuntu)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'